package kz.aita

internal fun appStateMessageTemplates() = listOf(
    EventMessageTemplate("app_state.title", "App state", "Состояние приложения", "Қолданба күйі", ky = "Колдонмонун абалы", tg = "Ҳолати барнома", uz = "Ilova holati"),
    EventMessageTemplate("app_state.help", "Save navigation, searches and unfinished form drafts for this account, app mode and store.", "Сохраняйте навигацию, поиск и незавершённые формы для этого аккаунта, режима и магазина.", "Осы аккаунт, режим және дүкен үшін навигацияны, іздеуді және толтырылмаған пішіндерді сақтаңыз.", ky = "Бул аккаунт, режим жана дүкөн үчүн навигацияны, издөөнү жана бүтө элек формаларды сактаңыз.", tg = "Паймоиш, ҷустуҷӯ ва шаклҳои нотамомро барои ин ҳисоб, реҷа ва мағоза захира кунед.", uz = "Bu hisob, rejim va do‘kon uchun navigatsiya, qidiruv va tugallanmagan shakllarni saqlang."),
    EventMessageTemplate("app_state.device", "Save on this device", "Сохранять на этом устройстве", "Осы құрылғыда сақтау", ky = "Бул түзмөктө сактоо", tg = "Захира дар ин дастгоҳ", uz = "Shu qurilmada saqlash"),
    EventMessageTemplate("app_state.cloud", "Save to my account", "Сохранять в аккаунте", "Аккаунтымда сақтау", ky = "Аккаунтумда сактоо", tg = "Захира дар ҳисоби ман", uz = "Hisobimda saqlash"),
    EventMessageTemplate("app_state.cloud_help", "Account saving restores your state after signing in on another device. Turning it off removes the saved account copy when the server is reachable.", "Сохранение в аккаунте восстанавливает состояние после входа на другом устройстве. Отключение удаляет копию на сервере при доступном соединении.", "Аккаунтта сақтау басқа құрылғыға кіргенде күйді қалпына келтіреді. Өшіргенде байланыс бар болса сервердегі көшірме жойылады.", ky = "Аккаунтта сактоо башка түзмөккө киргенде абалды калыбына келтирет. Өчүргөндө байланыш бар болсо сервердеги көчүрмө өчөт.", tg = "Захира дар ҳисоб ҳолатро баъди воридшавӣ аз дастгоҳи дигар барқарор мекунад. Хомӯшкунӣ нусхаи серверро ҳангоми дастрасии пайвастшавӣ нест мекунад.", uz = "Hisobda saqlash boshqa qurilmada kirganda holatni tiklaydi. O‘chirilsa, aloqa mavjud bo‘lganda serverdagi nusxa o‘chiriladi."),
    EventMessageTemplate("app_state.exclusions", "Carts, unsent transactions and recovery records remain saved on this device. Passwords, sign-in codes and payment screens are never included in account state.", "Корзины, неотправленные операции и данные восстановления остаются на устройстве. Пароли, коды входа и экраны оплаты не входят в состояние аккаунта.", "Себеттер, жіберілмеген операциялар және қалпына келтіру деректері құрылғыда қалады. Құпиясөздер, кіру кодтары және төлем экрандары аккаунт күйіне кірмейді.", ky = "Себеттер, жөнөтүлбөгөн операциялар жана калыбына келтирүү дайындары түзмөктө калат. Сырсөздөр, кирүү коддору жана төлөм экрандары аккаунт абалына кирбейт.", tg = "Сабадҳо, амалиёти ирсолнашуда ва маълумоти барқарорсозӣ дар дастгоҳ мемонанд. Рамзҳо, кодҳои воридшавӣ ва экранҳои пардохт ба ҳолати ҳисоб дохил намешаванд.", uz = "Savatlar, yuborilmagan amallar va tiklash yozuvlari qurilmada qoladi. Parollar, kirish kodlari va to‘lov ekranlari hisob holatiga kiritilmaydi."),
    EventMessageTemplate("app_state.loading", "Loading saved state…", "Загрузка состояния…", "Сақталған күй жүктелуде…", ky = "Сакталган абал жүктөлүүдө…", tg = "Боргирии ҳолати захирашуда…", uz = "Saqlangan holat yuklanmoqda…"),
    EventMessageTemplate("app_state.local", "Account saving is off", "Сохранение в аккаунте отключено", "Аккаунтта сақтау өшірулі", ky = "Аккаунтта сактоо өчүрүлгөн", tg = "Захира дар ҳисоб хомӯш аст", uz = "Hisobda saqlash o‘chiq"),
    EventMessageTemplate("app_state.saved", "Account copy is up to date", "Копия в аккаунте актуальна", "Аккаунттағы көшірме өзекті", ky = "Аккаунттагы көчүрмө жаңыртылган", tg = "Нусхаи ҳисоб нав аст", uz = "Hisobdagi nusxa dolzarb"),
    EventMessageTemplate("app_state.pending", "Waiting to save", "Ожидание сохранения", "Сақтауды күту", ky = "Сактоо күтүлүүдө", tg = "Интизори захира", uz = "Saqlash kutilmoqda"),
    EventMessageTemplate("app_state.unavailable", "Account sync is unavailable. Current work is kept; we will retry.", "Синхронизация недоступна. Текущая работа сохранена в приложении; повторим попытку.", "Синхрондау қолжетімсіз. Ағымдағы жұмыс қолданбада сақталды; қайта көреміз.", ky = "Шайкештештирүү жеткиликсиз. Учурдагы иш колдонмодо сакталды; кайра аракет кылабыз.", tg = "Ҳамоҳангсозӣ дастнорас аст. Кори ҷорӣ дар барнома нигоҳ дошта шуд; боз кӯшиш мекунем.", uz = "Sinxronlash mavjud emas. Joriy ish ilovada saqlandi; qayta urinib ko‘ramiz."),
    EventMessageTemplate("app_state.sign_in", "Sign in to restore state across devices", "Войдите для восстановления на других устройствах", "Басқа құрылғыларда қалпына келтіру үшін кіріңіз", ky = "Башка түзмөктөрдө калыбына келтирүү үчүн кириңиз", tg = "Барои барқарорсозӣ дар дастгоҳҳои дигар ворид шавед", uz = "Boshqa qurilmalarda tiklash uchun kiring"),
    EventMessageTemplate("app_state.too_large", "These drafts exceed the account storage limit. Finish or clear unused drafts before syncing.", "Черновики превышают лимит. Завершите или очистите ненужные черновики перед синхронизацией.", "Нобайлар шектен асты. Синхрондау алдында қажетсіз нобайларды аяқтаңыз не тазалаңыз.", ky = "Долбоорлор чектен ашты. Шайкештештирүүдөн мурун керексиз долбоорлорду бүтүрүңүз же тазалаңыз.", tg = "Пешнависҳо аз ҳад зиёданд. Пеш аз ҳамоҳангсозӣ пешнависҳои нолозимро анҷом диҳед ё тоза кунед.", uz = "Qoralamalar limitdan oshdi. Sinxronlashdan oldin keraksiz qoralamalarni tugating yoki tozalang."),
    EventMessageTemplate("app_state.conflict", "Another device saved different work. Choose which copy to continue with.", "На другом устройстве сохранены другие изменения. Выберите копию для продолжения.", "Басқа құрылғыда өзгеше жұмыс сақталған. Жалғастыру үшін көшірмені таңдаңыз.", ky = "Башка түзмөктө башка өзгөрүүлөр сакталган. Улантуу үчүн көчүрмөнү тандаңыз.", tg = "Дар дастгоҳи дигар кори дигар захира шудааст. Нусхаро барои идома интихоб кунед.", uz = "Boshqa qurilmada boshqa ish saqlangan. Davom etish uchun nusxani tanlang."),
    EventMessageTemplate("app_state.keep_device", "Keep this device’s work", "Оставить работу этого устройства", "Осы құрылғыдағы жұмысты қалдыру", ky = "Бул түзмөктөгү ишти калтыруу", tg = "Нигоҳ доштани кори ин дастгоҳ", uz = "Shu qurilmadagi ishni saqlash"),
    EventMessageTemplate("app_state.use_account", "Restore account copy", "Восстановить копию аккаунта", "Аккаунт көшірмесін қалпына келтіру", ky = "Аккаунт көчүрмөсүн калыбына келтирүү", tg = "Барқарор кардани нусхаи ҳисоб", uz = "Hisob nusxasini tiklash")
)
