package kz.aita

internal fun checkoutCartMessageTemplates() = listOf(
    EventMessageTemplate("checkout.ui.select_supplier", "Select supplier", "Выбрать поставщика", "Жеткізушіні таңдау", ky = "Жеткирүүчүнү тандоо", tg = "Интихоби таъминкунанда", uz = "Yetkazib beruvchini tanlash"),
    EventMessageTemplate("checkout.ui.add_cart", "Add cart", "Добавить корзину", "Себет қосу", ky = "Себет кошуу", tg = "Иловаи сабад", uz = "Savat qo‘shish"),
    EventMessageTemplate("checkout.ui.add_error", "Could not add a cart. Check available storage and try again.", "Не удалось добавить корзину. Проверьте свободное место и повторите попытку.", "Себет қосылмады. Бос орынды тексеріп, қайталап көріңіз.", ky = "Себет кошулган жок. Бош орунду текшерип, кайра аракет кылыңыз.", tg = "Сабад илова нашуд. Ҷойи холиро санҷида, боз кӯшиш кунед.", uz = "Savat qo‘shilmadi. Bo‘sh joyni tekshirib, qayta urinib ko‘ring."),
    EventMessageTemplate("checkout.ui.save_error", "Could not save the cart. The previous saved state is unchanged.", "Не удалось сохранить корзину. Предыдущее сохранённое состояние не изменено.", "Себет сақталмады. Бұрын сақталған күй өзгерген жоқ.", ky = "Себет сакталган жок. Мурда сакталган абал өзгөргөн жок.", tg = "Сабад захира нашуд. Ҳолати пешинаи захирашуда тағйир наёфт.", uz = "Savat saqlanmadi. Avval saqlangan holat o‘zgarmadi."),
    EventMessageTemplate("checkout.ui.restore_error", "Saved carts could not be loaded. They have not been replaced. Retry to restore them.", "Сохранённые корзины не удалось загрузить. Они не заменены пустыми. Повторите восстановление.", "Сақталған себеттер жүктелмеді. Олар бос себеттермен ауыстырылған жоқ. Қалпына келтіруді қайталаңыз.", ky = "Сакталган себеттер жүктөлгөн жок. Алар бош себеттерге алмаштырылган жок. Калыбына келтирүүнү кайталаңыз.", tg = "Сабадҳои захирашуда бор нашуданд. Онҳо бо сабадҳои холӣ иваз нашудаанд. Барқароркуниро такрор кунед.", uz = "Saqlangan savatlar yuklanmadi. Ular bo‘sh savatlar bilan almashtirilmadi. Tiklashni qayta sinang."),
    EventMessageTemplate("checkout.ui.retry", "Retry", "Повторить", "Қайталау", ky = "Кайталоо", tg = "Такрор", uz = "Qayta urinish"),
    EventMessageTemplate("checkout.ui.limit", "This transaction type has reached the limit of 1,000 carts.", "Для этого типа операций достигнут предел — 1000 корзин.", "Бұл операция түрі үшін 1000 себет шегіне жетті.", ky = "Бул операция түрү үчүн 1000 себет чегине жетти.", tg = "Барои ин навъи амалиёт ҳадди 1000 сабад расид.", uz = "Bu amaliyot turi uchun 1000 ta savat chegarasiga yetildi.")
)
