package kz.aita

internal fun companySupportMessageTemplates() = listOf(
    EventMessageTemplate("support.denied", "This support workspace is not available to your current employment or assignment.", "Это рабочее место недоступно по вашему текущему трудоустройству или назначению.", "Бұл жұмыс орны қазіргі қызметіңізге немесе тағайындауыңызға қолжетімсіз.", ky = "Бул колдоо иш мейкиндиги учурдагы жумуш ордуңуз же тапшырмаңыз үчүн жеткиликсиз."),
    EventMessageTemplate("support.invalid", "Check the message and request details. Messages can contain up to 4,000 characters.", "Проверьте сообщение и данные запроса. В сообщении может быть до 4 000 символов.", "Хабарламаны және сұрау деректерін тексеріңіз. Хабарламада 4 000 таңбаға дейін болуы мүмкін.", ky = "Билдирүүнү жана суроо-талаптын чоо-жайын текшериңиз. Билдирүү эң көп 4,000 белгиден турушу мүмкүн."),
    EventMessageTemplate("support.missing", "This conversation is not available to this account.", "Этот диалог недоступен этому аккаунту.", "Бұл диалог осы аккаунтқа қолжетімсіз.", ky = "Бул аккаунтка маек жеткиликсиз."),
    EventMessageTemplate("support.command_required", "Update the app before sending this support message.", "Обновите приложение перед отправкой сообщения в поддержку.", "Қолдау қызметіне хабарлама жіберер алдында қолданбаны жаңартыңыз.", ky = "Бул колдоо билдирүүсүн жөнөтүүдөн мурун колдонмону жаңыртыңыз."),
    EventMessageTemplate("support.command_conflict", "This message identifier was already used with different content. Check the conversation before sending again.", "Этот идентификатор сообщения уже использован с другим текстом. Проверьте диалог перед повторной отправкой.", "Бұл хабарлама идентификаторы басқа мәтінмен қолданылған. Қайта жіберер алдында диалогты тексеріңіз.", ky = "Бул билдирүү идентификатору башка мазмун менен колдонулган. Кайра жөнөтүүдөн мурун маекти текшериңиз."),
    EventMessageTemplate("support.reply_unavailable", "Reopen the conversation or claim it before replying.", "Откройте диалог заново или возьмите его в работу перед ответом.", "Жауап берер алдында диалогты қайта ашыңыз немесе жұмысқа алыңыз.", ky = "Жооп берүүдөн мурун маекти кайра ачыңыз же өзүңүзгө алыңыз."),
    EventMessageTemplate("support.changed", "The conversation changed on another device. Refresh before repeating the action.", "Диалог изменился на другом устройстве. Обновите его перед повторным действием.", "Диалог басқа құрылғыда өзгерді. Әрекетті қайталамас бұрын жаңартыңыз.", ky = "Маек башка түзмөктө өзгөрдү. Аракетти кайталоодон мурун жаңыртыңыз."),
    EventMessageTemplate("support.claimed", "Another agent is already working on this conversation.", "Этот диалог уже в работе у другого специалиста.", "Бұл диалогпен басқа маман жұмыс істеп жатыр.", ky = "Бул маек менен башка агент иштеп жатат."),
    EventMessageTemplate("support.own_ticket", "Use your customer chat for your own request. Another agent must handle it.", "Для своего обращения используйте клиентский чат. Его должен обработать другой специалист.", "Өз өтінішіңіз үшін клиенттік чатты пайдаланыңыз. Оны басқа маман өңдеуі керек.", ky = "Жеке өтүнүчүңүз үчүн кардар чатыңызды колдонуңуз. Аны башка агент карашы керек."),
    EventMessageTemplate("support.rate_limited", "Too many support requests. Wait a little and try again.", "Слишком много запросов в поддержку. Немного подождите и повторите.", "Қолдауға тым көп сұрау жіберілді. Сәл күтіп, қайталап көріңіз.", ky = "Колдоо өтүнүчтөрү өтө көп. Бир аз күтүп, кайра аракет кылыңыз."),
    EventMessageTemplate("support.save_failed", "Could not save the local message state safely. Keep this draft and check the conversation before sending again.", "Не удалось безопасно сохранить состояние сообщения. Сохраните черновик и проверьте диалог перед повторной отправкой.", "Хабарлама күйі қауіпсіз сақталмады. Мәтінді сақтап, қайта жіберер алдында диалогты тексеріңіз.", ky = "Билдирүүнүн жергиликтүү абалын коопсуз сактоо мүмкүн болгон жок. Бул долбоорду сактап, кайра жөнөтүүдөн мурун маекти текшериңиз."),
    EventMessageTemplate("support.send_unknown", "Sending is not confirmed. Retry the same saved message, not a new copy.", "Отправка не подтверждена. Повторите отправку сохранённого сообщения, не создавая копию.", "Жіберу расталмады. Жаңа көшірме жасамай, сақталған хабарламаны қайталаңыз.", ky = "Жөнөтүү ырасталган жок. Жаңы нусканы эмес, ошол эле сакталган билдирүүнү кайра жөнөтүңүз.")
)
