package kz.aita

internal fun deviceWorkflowMessageTemplates() = listOf(
    EventMessageTemplate("device.workflow.raw_receipt_help", "Direct ESC/POS queue · use only for printers that accept ESC/POS commands. Otherwise select System printer driver.", "Прямая очередь ESC/POS · только для принтеров с поддержкой команд ESC/POS. Иначе выберите системный драйвер.", "Тікелей ESC/POS кезегі · тек ESC/POS пәрмендерін қолдайтын принтерлер үшін. Әйтпесе жүйелік драйверді таңдаңыз.", ky = "Түз ESC/POS кезеги · ESC/POS буйруктарын колдогон принтерлер үчүн гана. Болбосо системалык драйверди тандаңыз.", tg = "Навбати мустақими ESC/POS · танҳо барои чопгарҳои дорои дастгирии фармонҳои ESC/POS. Дар акси ҳол драйвери системаро интихоб кунед.", uz = "Bevosita ESC/POS navbati · faqat ESC/POS buyruqlarini qabul qiladigan printerlar uchun. Aks holda tizim drayverini tanlang."),
    EventMessageTemplate("device.workflow.desktop_system_print", "System printer driver · choose at print time", "Системный драйвер · выбор принтера при печати", "Жүйелік драйвер · принтерді басып шығарғанда таңдау", ky = "Системалык драйвер · принтерди басып чыгарууда тандоо", tg = "Драйвери система · интихоби чопгар ҳангоми чоп", uz = "Tizim drayveri · chop etishda printerni tanlash"),
    EventMessageTemplate("device.workflow.receipt_paper", "Receipt roll width", "Ширина чековой ленты", "Чек таспасының ені", ky = "Чек тасмасынын туурасы", tg = "Паҳнои тасмаи расид", uz = "Chek lentasi kengligi"),
    EventMessageTemplate("device.workflow.receipt_system_help", "Select your thermal printer in the print dialog, then the matching 58 or 80 mm roll size. Use 100% scale and turn off headers and footers. USB printers need their system driver. The browser cannot list or identify installed printers itself.", "Выберите термопринтер в диалоге печати и подходящую ленту 58 или 80 мм. Установите масштаб 100% и отключите колонтитулы. Для USB-принтера нужен системный драйвер. Сам браузер не может перечислять или определять установленные принтеры.", "Басып шығару терезесінде термопринтер мен сәйкес 58 немесе 80 мм таспаны таңдаңыз. Масштабты 100% етіп, колонтитулдарды өшіріңіз. USB принтеріне жүйелік драйвер қажет. Браузер орнатылған принтерлерді өзі тізімдей не анықтай алмайды.", ky = "Басып чыгаруу терезесинен термопринтерди жана туура келген 58 же 80 мм тасманы тандаңыз. Масштабды 100% кылып, колонтитулдарды өчүрүңүз. USB принтерге системалык драйвер керек. Браузер орнотулган принтерлерди өзү тизмелей же аныктай албайт.", tg = "Дар равзанаи чоп термопринтер ва тасмаи мувофиқи 58 ё 80 мм-ро интихоб кунед. Миқёсро 100% карда, сарлавҳа ва поённависро хомӯш кунед. Чопгари USB драйвери система мехоҳад. Браузер худаш чопгарҳои насбшударо номбар ё муайян карда наметавонад.", uz = "Chop etish oynasida termoprinterni va mos 58 yoki 80 mm lentani tanlang. Masshtabni 100% qilib, kolontitullarni o‘chiring. USB printerga tizim drayveri kerak. Brauzer o‘rnatilgan printerlarni o‘zi ro‘yxatlay yoki aniqlay olmaydi."),
    EventMessageTemplate("device.workflow.receipt_driver_help", "Choose any installed receipt printer in the system print dialog, including USB models that need their manufacturer driver. Set the matching roll size in printer properties. Existing direct ESC/POS selections still print directly.", "Выберите установленный чековый принтер в системном диалоге печати, включая USB-модели с драйвером производителя. Укажите нужный размер ленты в свойствах принтера. Ранее выбранные прямые подключения ESC/POS продолжают печатать напрямую.", "Жүйелік басып шығару терезесінде орнатылған чек принтерін, соның ішінде өндіруші драйверін қажет ететін USB үлгілерін таңдаңыз. Принтер қасиеттерінде сәйкес таспа өлшемін орнатыңыз. Бұрын таңдалған ESC/POS қосылымдары тікелей басып шығара береді.", ky = "Системалык басып чыгаруу терезесинен орнотулган чек принтерин, анын ичинде өндүрүүчүнүн драйверин талап кылган USB үлгүлөрүн тандаңыз. Принтердин касиеттеринен туура тасманын өлчөмүн коюңуз. Мурда тандалган ESC/POS түз байланыштары түз басып чыгара берет.", tg = "Дар равзанаи системавии чоп чопгари расиди насбшударо, аз ҷумла моделҳои USB бо драйвери истеҳсолкунанда, интихоб кунед. Дар хусусиятҳои чопгар андозаи мувофиқи тасмаро гузоред. Пайвастҳои мустақими интихобшудаи ESC/POS мустақим чоп мекунанд.", uz = "Tizim chop etish oynasida o‘rnatilgan chek printerini, jumladan ishlab chiqaruvchi drayveriga muhtoj USB modellarini tanlang. Printer xususiyatlarida mos lenta o‘lchamini belgilang. Avval tanlangan bevosita ESC/POS ulanishlari bevosita chop etishda davom etadi."),
    EventMessageTemplate("device.workflow.label_system_help", "Choose your label printer and the label size in the print dialog. Keep 100% scale and disable headers and footers. AITA prepares adhesive labels at their actual dimensions, not A4 sheets.", "Выберите принтер этикеток и размер этикетки в диалоге печати. Оставьте масштаб 100% и отключите колонтитулы. AITA готовит самоклеящиеся этикетки в их реальном размере, а не на листах A4.", "Басып шығару терезесінде жапсырма принтері мен жапсырма өлшемін таңдаңыз. Масштабты 100% етіп, колонтитулдарды өшіріңіз. AITA жапсырмаларды A4 парағына емес, нақты өлшемімен дайындайды.", ky = "Басып чыгаруу терезесинен этикетка принтерин жана этикетканын өлчөмүн тандаңыз. Масштабды 100% кылып, колонтитулдарды өчүрүңүз. AITA жабышма этикеткаларды A4 барагында эмес, чыныгы өлчөмүндө даярдайт.", tg = "Дар равзанаи чоп чопгари тамға ва андозаи тамғаро интихоб кунед. Миқёсро 100% нигоҳ дошта, сарлавҳа ва поённависро хомӯш кунед. AITA тамғаҳои часпандаро бо андозаи аслӣ, на дар варақи A4, омода мекунад.", uz = "Chop etish oynasida yorliq printeri va yorliq o‘lchamini tanlang. Masshtabni 100% qilib, kolontitullarni o‘chiring. AITA yopishqoq yorliqlarni A4 varag‘ida emas, haqiqiy o‘lchamida tayyorlaydi."),
    EventMessageTemplate("device.workflow.print_busy", "Another print dialog is already open", "Другой диалог печати уже открыт", "Басқа басып шығару терезесі ашық", ky = "Башка басып чыгаруу терезеси ачык", tg = "Равзанаи дигари чоп аллакай кушода аст", uz = "Boshqa chop etish oynasi allaqachon ochiq"),
    EventMessageTemplate("device.workflow.print_cancelled", "Printing cancelled", "Печать отменена", "Басып шығару тоқтатылды", ky = "Басып чыгаруу жокко чыгарылды", tg = "Чоп бекор шуд", uz = "Chop etish bekor qilindi"),
    EventMessageTemplate("device.workflow.print_queued", "Document sent to the system print queue", "Документ отправлен в системную очередь печати", "Құжат жүйелік басып шығару кезегіне жіберілді", ky = "Документ системалык басып чыгаруу кезегине жөнөтүлдү", tg = "Ҳуҷҷат ба навбати системавии чоп фиристода шуд", uz = "Hujjat tizim chop etish navbatiga yuborildi"),
    EventMessageTemplate("device.workflow.driver_print_failed", "Could not print through the system driver. Check its print queue, driver, paper size and USB connection before retrying.", "Не удалось напечатать через системный драйвер. Перед повтором проверьте очередь печати, драйвер, размер бумаги и USB-подключение.", "Жүйелік драйвер арқылы басып шығару мүмкін болмады. Қайталаудан бұрын басып шығару кезегін, драйверді, қағаз өлшемін және USB қосылымын тексеріңіз.", ky = "Системалык драйвер аркылуу басып чыгаруу мүмкүн болгон жок. Кайталоодон мурун басып чыгаруу кезегин, драйверди, кагаздын өлчөмүн жана USB байланышын текшериңиз.", tg = "Тавассути драйвери система чоп нашуд. Пеш аз такрор навбати чоп, драйвер, андозаи коғаз ва пайвасти USB-ро санҷед.", uz = "Tizim drayveri orqali chop etib bo‘lmadi. Qayta urinishdan oldin chop etish navbati, drayver, qog‘oz o‘lchami va USB ulanishini tekshiring."),
    EventMessageTemplate("device.workflow.paper_save_failed", "Could not save the receipt paper setting on this device", "Не удалось сохранить размер чековой ленты на этом устройстве", "Осы құрылғыда чек таспасының өлшемін сақтау мүмкін болмады", ky = "Бул түзмөктө чек тасмасынын өлчөмүн сактоо мүмкүн болгон жок", tg = "Андозаи тасмаи расид дар ин дастгоҳ захира нашуд", uz = "Bu qurilmada chek lentasi o‘lchamini saqlab bo‘lmadi"),
    EventMessageTemplate("device.workflow.system_print", "Browser / system print dialog", "Диалог печати браузера / системы", "Браузер / жүйе басып шығару терезесі", ky = "Браузердин / системанын басып чыгаруу терезеси", tg = "Равзанаи чопи браузер / система", uz = "Brauzer / tizim chop etish oynasi"),
    EventMessageTemplate("device.workflow.system_print_help", "Choose an installed printer and its paper or label size in the print dialog. Install its system driver first if it is missing.", "Выберите установленный принтер и размер бумаги или этикетки в диалоге печати. Если принтера нет, сначала установите его системный драйвер.", "Басып шығару терезесінде орнатылған принтерді және қағаз не жапсырма өлшемін таңдаңыз. Принтер жоқ болса, алдымен оның жүйелік драйверін орнатыңыз.", ky = "Басып чыгаруу терезесинен орнотулган принтерди жана кагаздын же этикетканын өлчөмүн тандаңыз. Принтер жок болсо, адегенде анын системалык драйверин орнотуңуз.", tg = "Дар равзанаи чоп чопгари насбшуда ва андозаи коғаз ё тамғаро интихоб кунед. Агар чопгар набошад, аввал драйвери системавии онро насб кунед.", uz = "Chop etish oynasida o‘rnatilgan printer va qog‘oz yoki yorliq o‘lchamini tanlang. Printer bo‘lmasa, avval uning tizim drayverini o‘rnating."),
    EventMessageTemplate("device.workflow.print_opened", "Document opened for printing", "Документ открыт для печати", "Құжат басып шығару үшін ашылды", ky = "Документ басып чыгаруу үчүн ачылды", tg = "Ҳуҷҷат барои чоп кушода шуд", uz = "Hujjat chop etish uchun ochildi"),
    EventMessageTemplate("device.workflow.print_failed", "Could not open printing. Check browser printing permissions and try again.", "Не удалось открыть печать. Проверьте разрешения браузера на печать и повторите.", "Басып шығару ашылмады. Браузердің басып шығару рұқсаттарын тексеріп, қайталаңыз.", ky = "Басып чыгаруу ачылган жок. Браузердин басып чыгарууга уруксаттарын текшерип, кайра аракет кылыңыз.", tg = "Чоп кушода нашуд. Иҷозатҳои чопи браузерро санҷед ва боз кӯшиш кунед.", uz = "Chop etish ochilmadi. Brauzerning chop etish ruxsatlarini tekshirib, qayta urinib ko‘ring."),
    EventMessageTemplate("device.workflow.report_failed", "Could not perform the report action", "Не удалось выполнить действие с отчётом", "Есеппен әрекетті орындау мүмкін болмады", ky = "Отчёт менен аракетти аткаруу мүмкүн болгон жок", tg = "Амал бо ҳисобот иҷро нашуд", uz = "Hisobot bilan amalni bajarib bo‘lmadi"),
    EventMessageTemplate("device.workflow.discovery_unavailable", "Printer discovery is unavailable on this platform", "Поиск принтеров недоступен на этой платформе", "Бұл платформада принтерлерді іздеу қолжетімсіз", ky = "Бул платформада принтерлерди издөө жеткиликсиз", tg = "Дар ин платформа ҷустуҷӯи чопгарҳо дастрас нест", uz = "Bu platformada printerlarni qidirish mavjud emas"),
    EventMessageTemplate("device.workflow.sale_price_percent", "Quick fill · % of sale price", "Быстрое заполнение · % от цены продажи", "Жылдам толтыру · сату бағасының %", ky = "Тез толтуруу · сатуу баасынын %", tg = "Пуркунии зуд · % аз нархи фурӯш", uz = "Tez to‘ldirish · sotuv narxidan %"),
)
