package kz.aita

internal fun deviceWorkflowMessageTemplates() = listOf(
    EventMessageTemplate("device.workflow.system_print", "Browser / system print dialog", "Диалог печати браузера / системы", "Браузер / жүйе басып шығару терезесі", ky = "Браузердин / системанын басып чыгаруу терезеси", tg = "Равзанаи чопи браузер / система", uz = "Brauzer / tizim chop etish oynasi"),
    EventMessageTemplate("device.workflow.system_print_help", "Choose an installed printer and its paper or label size in the print dialog. Install its system driver first if it is missing.", "Выберите установленный принтер и размер бумаги или этикетки в диалоге печати. Если принтера нет, сначала установите его системный драйвер.", "Басып шығару терезесінде орнатылған принтерді және қағаз не жапсырма өлшемін таңдаңыз. Принтер жоқ болса, алдымен оның жүйелік драйверін орнатыңыз.", ky = "Басып чыгаруу терезесинен орнотулган принтерди жана кагаздын же этикетканын өлчөмүн тандаңыз. Принтер жок болсо, адегенде анын системалык драйверин орнотуңуз.", tg = "Дар равзанаи чоп чопгари насбшуда ва андозаи коғаз ё тамғаро интихоб кунед. Агар чопгар набошад, аввал драйвери системавии онро насб кунед.", uz = "Chop etish oynasida o‘rnatilgan printer va qog‘oz yoki yorliq o‘lchamini tanlang. Printer bo‘lmasa, avval uning tizim drayverini o‘rnating."),
    EventMessageTemplate("device.workflow.print_opened", "Document opened for printing", "Документ открыт для печати", "Құжат басып шығару үшін ашылды", ky = "Документ басып чыгаруу үчүн ачылды", tg = "Ҳуҷҷат барои чоп кушода шуд", uz = "Hujjat chop etish uchun ochildi"),
    EventMessageTemplate("device.workflow.print_failed", "Could not open printing. Check browser printing permissions and try again.", "Не удалось открыть печать. Проверьте разрешения браузера на печать и повторите.", "Басып шығару ашылмады. Браузердің басып шығару рұқсаттарын тексеріп, қайталаңыз.", ky = "Басып чыгаруу ачылган жок. Браузердин басып чыгарууга уруксаттарын текшерип, кайра аракет кылыңыз.", tg = "Чоп кушода нашуд. Иҷозатҳои чопи браузерро санҷед ва боз кӯшиш кунед.", uz = "Chop etish ochilmadi. Brauzerning chop etish ruxsatlarini tekshirib, qayta urinib ko‘ring."),
    EventMessageTemplate("device.workflow.report_failed", "Could not perform the report action", "Не удалось выполнить действие с отчётом", "Есеппен әрекетті орындау мүмкін болмады", ky = "Отчёт менен аракетти аткаруу мүмкүн болгон жок", tg = "Амал бо ҳисобот иҷро нашуд", uz = "Hisobot bilan amalni bajarib bo‘lmadi"),
    EventMessageTemplate("device.workflow.discovery_unavailable", "Printer discovery is unavailable on this platform", "Поиск принтеров недоступен на этой платформе", "Бұл платформада принтерлерді іздеу қолжетімсіз", ky = "Бул платформада принтерлерди издөө жеткиликсиз", tg = "Дар ин платформа ҷустуҷӯи чопгарҳо дастрас нест", uz = "Bu platformada printerlarni qidirish mavjud emas"),
    EventMessageTemplate("device.workflow.sale_price_percent", "Quick fill · % of sale price", "Быстрое заполнение · % от цены продажи", "Жылдам толтыру · сату бағасының %", ky = "Тез толтуруу · сатуу баасынын %", tg = "Пуркунии зуд · % аз нархи фурӯш", uz = "Tez to‘ldirish · sotuv narxidan %"),
)
