package kz.aita

internal fun marketplaceEventMessageTemplates() = listOf(
    EventMessageTemplate("market.invalid", "Check the shop-window details. A name, city and public pickup address are required before publishing.", "Проверьте данные витрины. Для публикации нужны название, город и публичный адрес самовывоза.", "Витрина деректерін тексеріңіз. Жариялау үшін атау, қала және алып кету мекенжайы қажет."),
    EventMessageTemplate("market.owner", "Only a store owner can publish this location's shop window.", "Опубликовать витрину этой точки может только владелец магазина.", "Осы нүктенің витринасын тек дүкен иесі жариялай алады."),
    EventMessageTemplate("market.changed", "This publication changed on another device. Reload it before saving again.", "Публикация изменилась на другом устройстве. Обновите данные перед сохранением.", "Жарияланым басқа құрылғыда өзгерді. Сақтамас бұрын деректерді жаңартыңыз."),
    EventMessageTemplate("market.unavailable", "This offer is no longer published or available to view.", "Это предложение больше не опубликовано или недоступно для просмотра.", "Бұл ұсыныс енді жарияланбаған немесе көруге қолжетімсіз."),
    EventMessageTemplate("market.saved_limit", "Your saved list can contain up to 100 offers. Remove one before adding another.", "Можно сохранить до 100 предложений. Удалите одно, чтобы добавить новое.", "100 ұсынысқа дейін сақтауға болады. Жаңасын қосу үшін біреуін өшіріңіз."),
    EventMessageTemplate("market.listing_limit", "This location can publish up to 1,000 listings in the preview.", "В предварительной версии эта точка может опубликовать до 1 000 товаров.", "Алдын ала нұсқада осы нүкте 1 000 тауарға дейін жариялай алады."),
    EventMessageTemplate("market.refresh_failed", "Could not refresh these offers. Previously displayed data may be out of date.", "Не удалось обновить предложения. Ранее показанные данные могли устареть.", "Ұсыныстарды жаңарту мүмкін болмады. Бұрын көрсетілген деректер ескіруі мүмкін."),
    EventMessageTemplate("market.page_changed", "The result pages changed while loading. Refresh or narrow your search.", "Страницы результатов изменились во время загрузки. Обновите данные или уточните поиск.", "Жүктеу кезінде нәтиже беттері өзгерді. Жаңартыңыз немесе іздеуді нақтылаңыз."),
    EventMessageTemplate("market.shop_unavailable", "This shop window is no longer published or available.", "Эта витрина больше не опубликована или недоступна.", "Бұл витрина енді жарияланбаған немесе қолжетімсіз."),
    EventMessageTemplate("market.shopping_invalid", "Check the shopping-list quantity and selling unit.", "Проверьте количество и единицу продажи в списке покупок.", "Сатып алу тізіміндегі сан мен сату бірлігін тексеріңіз."),
    EventMessageTemplate("market.shopping_denied", "Sign in again to open your shopping list.", "Войдите снова, чтобы открыть свой список покупок.", "Сатып алу тізімін ашу үшін қайта кіріңіз."),
    EventMessageTemplate("market.shopping_changed", "Your list changed on another device. The latest list is loaded; review it before trying your edit again.", "Список изменился на другом устройстве. Загружена новая версия; проверьте её перед повторным изменением.", "Тізім басқа құрылғыда өзгерді. Жаңа нұсқа жүктелді; қайта өзгертпес бұрын тексеріңіз."),
    EventMessageTemplate("market.shopping_basis_changed", "The selling unit or product identity changed. Review the current offer; remove the old line before adding it with the new unit.", "Изменилась единица продажи или идентификация товара. Проверьте предложение; удалите старую строку перед добавлением с новой единицей.", "Сату бірлігі немесе тауар сәйкестігі өзгерді. Ұсынысты тексеріп, жаңа бірлікпен қоспас бұрын ескі жолды жойыңыз."),
    EventMessageTemplate("market.shopping_limit", "Your shopping list can contain up to 50 offers. Remove one before adding another.", "В списке покупок может быть до 50 предложений. Удалите одно перед добавлением нового.", "Сатып алу тізімінде 50 ұсынысқа дейін болуы мүмкін. Жаңасын қоспас бұрын біреуін жойыңыз."),
    EventMessageTemplate("market.shopping_command_mismatch", "This saved change has a conflicting identity. Keep it for support review; it has not been resubmitted as a new change.", "У сохранённого изменения конфликт идентификатора. Сохраните его для поддержки; новое изменение вместо него не отправлено.", "Сақталған өзгеріс идентификаторында қайшылық бар. Қолдау қызметіне сақтаңыз; оның орнына жаңа өзгеріс жіберілген жоқ."),
    EventMessageTemplate("market.shopping_storage", "The shopping list could not be saved on this device. No local success is assumed; a previously saved unconfirmed change remains recoverable.", "Не удалось сохранить список покупок на устройстве. Неподтверждённое изменение сохранено для восстановления, если запись была выполнена ранее.", "Сатып алу тізімін құрылғыда сақтау мүмкін болмады. Бұрын жазылған расталмаған өзгеріс қалпына келтіруге сақталады."),
    EventMessageTemplate("market.shopping_pending", "A list change is not confirmed yet. Retry that same change before making another; a network failure does not mean it was rejected.", "Изменение списка пока не подтверждено. Повторите его перед следующим изменением: сбой сети не означает отказ.", "Тізім өзгерісі әлі расталмады. Келесі өзгеріске дейін сол өзгерісті қайталаңыз: желі қатесі бас тартуды білдірмейді."),
    EventMessageTemplate("market.shopping_refresh", "Could not refresh the shopping list. Saved estimates are not a current price or stock guarantee.", "Не удалось обновить список покупок. Сохранённый расчёт не гарантирует текущую цену и наличие.", "Сатып алу тізімін жаңарту мүмкін болмады. Сақталған есеп ағымдағы баға мен қордың кепілі емес."),
    EventMessageTemplate("market.comparison_invalid", "Choose an offer with a valid barcode, currency and selling unit to compare.", "Для сравнения выберите предложение с корректным штрихкодом, валютой и единицей продажи.", "Салыстыру үшін жарамды штрихкоды, валютасы және сату бірлігі бар ұсынысты таңдаңыз."),
    EventMessageTemplate("market.comparison_changed", "The product or selling unit changed. Close this comparison and review the current offer before trying again.", "Товар или единица продажи изменились. Закройте сравнение и проверьте актуальное предложение.", "Тауар немесе сату бірлігі өзгерді. Салыстыруды жауып, ағымдағы ұсынысты тексеріңіз."),
    EventMessageTemplate("market.comparison_refresh", "Could not refresh comparison. Previously shown estimates may be out of date.", "Не удалось обновить сравнение. Ранее показанные расчёты могли устареть.", "Салыстыруды жаңарту мүмкін болмады. Бұрын көрсетілген есептер ескіруі мүмкін."),
    EventMessageTemplate("market.comparison_already_listed", "That offer is already in your list. No lines were merged or removed.", "Это предложение уже в списке. Строки не объединены и не удалены.", "Бұл ұсыныс тізімде бар. Жолдар біріктірілген де, жойылған да жоқ."),
    EventMessageTemplate("market.comparison_unavailable", "The replacement cannot currently be estimated for this quantity. Your original line was kept.", "Замену сейчас нельзя рассчитать для этого количества. Исходная строка сохранена.", "Ауыстырылатын ұсынысты осы сан үшін қазір есептеу мүмкін емес. Бастапқы жол сақталды."),
    EventMessageTemplate("market.comparison_price_changed", "The replacement estimate changed after review. Your original line was kept; refresh and review again.", "Расчёт замены изменился после проверки. Исходная строка сохранена; обновите и проверьте снова.", "Тексергеннен кейін ауыстыру есебі өзгерді. Бастапқы жол сақталды; жаңартып, қайта тексеріңіз."),
    EventMessageTemplate("market.saved", "Shop-window changes saved.", "Изменения витрины сохранены.", "Витрина өзгерістері сақталды.")
)
