package kz.aita

internal fun notificationEventMessageTemplates() = listOf(
    EventMessageTemplate("app_state.navigation_local", "Your last screen is always remembered on this device, even when form saving is off.", "Последний экран всегда сохраняется на этом устройстве, даже если сохранение форм отключено.", "Пішіндерді сақтау өшірулі болса да, соңғы экран осы құрылғыда сақталады.", ky = "Формаларды сактоо өчүк болсо да, акыркы экран бул түзмөктө сакталат.", tg = "Экрани охирин ҳамеша дар ин дастгоҳ нигоҳ дошта мешавад, ҳатто агар нигоҳдории шаклҳо хомӯш бошад.", uz = "Shakllarni saqlash oʻchirilgan boʻlsa ham, oxirgi ekran shu qurilmada eslab qolinadi."),
    EventMessageTemplate("notifications.activity.title", "Store activity", "События магазина", "Дүкендегі оқиғалар", ky = "Дүкөндөгү окуялар", tg = "Рӯйдодҳои мағоза", uz = "Doʻkondagi voqealar"),
    EventMessageTemplate("notifications.activity.body", "Another user updated your store. Open the operation log for details.", "Другой пользователь внёс изменения в магазине. Подробности — в журнале операций.", "Басқа пайдаланушы дүкенге өзгеріс енгізді. Толығырақ операциялар журналында.", ky = "Башка колдонуучу дүкөнгө өзгөртүү киргизди. Кененирээк маалымат операциялар журналында.", tg = "Корбари дигар мағозаро нав кард. Тафсилотро дар сабти амалиёт бинед.", uz = "Boshqa foydalanuvchi doʻkonga oʻzgartirish kiritdi. Tafsilotlar amallar jurnalida."),
    EventMessageTemplate("notifications.missed", "{count} missed notifications", "Пропущено уведомлений: {count}", "Өткізіп алған хабарландырулар: {count}", ky = "Өткөрүп жиберилген билдирүүлөр: {count}", tg = "Огоҳиҳои аздастрафта: {count}", uz = "Oʻtkazib yuborilgan bildirishnomalar: {count}"),
    EventMessageTemplate("security.signin.title", "Sign-in on another device", "Вход на другом устройстве", "Басқа құрылғыдан кіру", ky = "Башка түзмөктөн кирүү", tg = "Воридшавӣ аз дастгоҳи дигар", uz = "Boshqa qurilmadan kirish"),
    EventMessageTemplate("security.signin.body", "Your account was signed in on {device}. If this was not you, open Security, revoke the session and change your password.", "В ваш аккаунт вошли с устройства {device}. Если это были не вы, откройте «Безопасность», завершите сеанс и смените пароль.", "Аккаунтыңызға {device} құрылғысынан кірді. Бұл сіз болмасаңыз, «Қауіпсіздік» бөлімінде сеансты аяқтап, құпия сөзді өзгертіңіз.", ky = "Аккаунтуңузга {device} түзмөгүнөн киришти. Бул сиз болбосоңуз, «Коопсуздук» бөлүмүндө сессияны токтотуп, сырсөздү өзгөртүңүз.", tg = "Ба ҳисоби шумо аз {device} ворид шуданд. Агар ин шумо набудед, «Амният»-ро кушоед, сеансро қатъ кунед ва гузарвожаро иваз кунед.", uz = "Hisobingizga {device} qurilmasidan kirildi. Bu siz boʻlmasangiz, «Xavfsizlik» boʻlimida seansni tugatib, parolni oʻzgartiring."),
    EventMessageTemplate("security.signin.email", "Your AITA account was signed in on another device. If this was not you, open AITA → Menu → Account → Security, revoke unfamiliar sessions and change your password.", "В ваш аккаунт AITA вошли с другого устройства. Если это были не вы, откройте AITA → Меню → Аккаунт → Безопасность, завершите незнакомые сеансы и смените пароль.", "AITA аккаунтыңызға басқа құрылғыдан кірді. Бұл сіз болмасаңыз, AITA → Мәзір → Аккаунт → Қауіпсіздік бөлімін ашып, бейтаныс сеанстарды аяқтаңыз және құпия сөзді өзгертіңіз.", ky = "AITA аккаунтуңузга башка түзмөктөн киришти. Бул сиз болбосоңуз, AITA → Меню → Аккаунт → Коопсуздук бөлүмүндө бейтааныш сессияларды токтотуп, сырсөздү өзгөртүңүз.", tg = "Ба ҳисоби AITA-и шумо аз дастгоҳи дигар ворид шуданд. Агар ин шумо набудед, AITA → Меню → Ҳисоб → Амният-ро кушоед, сеансҳои ношиносро қатъ кунед ва гузарвожаро иваз кунед.", uz = "AITA hisobingizga boshqa qurilmadan kirildi. Bu siz boʻlmasangiz, AITA → Menyu → Hisob → Xavfsizlik boʻlimida notanish seanslarni tugatib, parolni oʻzgartiring."),
    EventMessageTemplate("return.quantity_limit", "Choose a return quantity within the receipt amount", "Укажите количество возврата в пределах количества в чеке", "Қайтару санын чектегі мөлшерден асырмаңыз", ky = "Кайтаруу санын чектеги өлчөмдөн ашырбаңыз", tg = "Миқдори баргардониро дар ҳудуди миқдори расид интихоб кунед", uz = "Qaytarish miqdorini chekdagi miqdor doirasida tanlang")
)
