package kz.aita

internal fun storeArchitectureMessageTemplates() = listOf(
    EventMessageTemplate("store.branch_type", "Branch type", "Тип филиала", "Филиал түрі", ky = "Филиалдын түрү", tg = "Навъи филиал", uz = "Filial turi"),
    EventMessageTemplate("store.branch.physical", "Physical branch", "Физический филиал", "Физикалық филиал", ky = "Физикалык филиал", tg = "Филиали ҷисмонӣ", uz = "Jismoniy filial"),
    EventMessageTemplate("store.branch.internet", "Internet branch", "Интернет-филиал", "Интернет-филиал", ky = "Интернет-филиал", tg = "Филиали интернетӣ", uz = "Internet filiali"),
    EventMessageTemplate("store.management", "Management & warehouse", "Управление и склад", "Басқару және қойма", ky = "Башкаруу жана кампа", tg = "Идоракунӣ ва анбор", uz = "Boshqaruv va ombor"),
    EventMessageTemplate("store.management_help", "Manage your branches and warehouse here. Sales and subscriptions belong to each branch.", "Здесь находятся управление филиалами и склад. Продажи и подписки относятся к каждому филиалу.", "Мұнда филиалдар мен қойманы басқарыңыз. Сатылымдар мен жазылымдар әр филиалға тиесілі.", ky = "Бул жерден филиалдарды жана кампаны башкарыңыз. Сатуулар жана жазылуулар ар бир филиалга тиешелүү.", tg = "Дар ин ҷо филиалҳо ва анборро идора кунед. Фурӯш ва обунаҳо ба ҳар филиал тааллуқ доранд.", uz = "Bu yerda filiallar va omborni boshqaring. Savdolar va obunalar har bir filialga tegishli."),
    EventMessageTemplate("store.branch_help", "Physical branches serve customers in store. Internet branches publish a marketplace storefront and choose its pickup locations. Each branch has its own subscription.", "Физические филиалы обслуживают покупателей на месте. Интернет-филиалы публикуют магазин на маркетплейсе и выбирают места получения товаров. У каждого филиала своя подписка.", "Физикалық филиалдар сатып алушыларға дүкенде қызмет көрсетеді. Интернет-филиалдар маркетплейсте дүкен жариялап, тауарды алу орындарын таңдайды. Әр филиалдың өз жазылымы бар.", ky = "Физикалык филиалдар кардарларды дүкөндө тейлейт. Интернет-филиалдар маркетплейсте дүкөн жарыялап, товарды алуу жайларын тандайт. Ар бир филиалдын өз жазылуусу бар.", tg = "Филиалҳои ҷисмонӣ ба харидорон дар мағоза хизмат мерасонанд. Филиалҳои интернетӣ дар маркетплейс мағоза нашр карда, ҷойҳои гирифтани молро интихоб мекунанд. Ҳар филиал обунаи худро дорад.", uz = "Jismoniy filiallar xaridorlarga do‘konda xizmat ko‘rsatadi. Internet filiallari marketpleysda do‘konni e’lon qilib, tovar olish joylarini tanlaydi. Har bir filialning o‘z obunasi bor."),
    EventMessageTemplate("store.operating_branch_required", "Choose a branch for transactions and payments", "Для операций и платежей выберите филиал", "Операциялар мен төлемдер үшін филиалды таңдаңыз", ky = "Операциялар жана төлөмдөр үчүн филиалды тандаңыз", tg = "Барои амалиёт ва пардохтҳо филиалро интихоб кунед", uz = "Amaliyotlar va to‘lovlar uchun filialni tanlang"),
    EventMessageTemplate("store.shared_catalogue_in_use", "Other branches still use this store's product records. Move their batches to their own product records before deleting this store.", "Другие филиалы ещё используют карточки товаров этого магазина. Перед удалением магазина перенесите их партии в собственные карточки товаров.", "Басқа филиалдар осы дүкеннің тауар карточкаларын әлі қолданады. Дүкенді жоймас бұрын олардың партияларын өз тауар карточкаларына көшіріңіз.", ky = "Башка филиалдар бул дүкөндүн товар карточкаларын дагы колдонууда. Дүкөндү өчүрүүдөн мурун алардын партияларын өз товар карточкаларына көчүрүңүз.", tg = "Филиалҳои дигар ҳанӯз сабтҳои моли ин мағозаро истифода мебаранд. Пеш аз нест кардани мағоза партияҳои онҳоро ба сабтҳои моли худ гузаронед.", uz = "Boshqa filiallar hali bu do‘konning tovar kartalaridan foydalanadi. Do‘konni o‘chirishdan oldin ularning partiyalarini o‘z tovar kartalariga ko‘chiring."),
)
