package kz.aita

internal fun subscriptionEventMessageTemplates(): List<EventMessageTemplate> = listOf(
    EventMessageTemplate("subscription.result_unknown", "This request has no confirmed result yet. Check its status before reviewing another offer.", "Результат запроса пока не подтверждён. Проверьте его статус перед новым предложением.", "Сұрау нәтижесі әлі расталмаған. Жаңа ұсынысты қараудан бұрын күйін тексеріңіз.", ky = "Бул суроо-талаптын ырасталган натыйжасы азырынча жок. Башка сунушту кароодон мурун анын статусун текшериңиз."),
    EventMessageTemplate("subscription.journal_failed", "Could not safely save this subscription request on this device. Nothing was submitted.", "Не удалось безопасно сохранить запрос на устройстве. Запрос не отправлен.", "Жазылым сұрауы құрылғыда сақталмады. Сұрау жіберілген жоқ.", ky = "Бул жазылуу суроо-талабын түзмөктө коопсуз сактоо мүмкүн болгон жок. Эч нерсе жөнөтүлгөн жок."),
    EventMessageTemplate("subscription.required", "An active subscription is required for this location. Open Subscription to activate access.", "Для этой точки нужна активная подписка. Откройте «Подписка», чтобы подключить доступ.", "Осы нүктеге белсенді жазылым қажет. Қолжетімділікті қосу үшін «Жазылымды» ашыңыз.", ky = "Бул жай үчүн активдүү жазылуу талап кылынат. Мүмкүнчүлүктү иштетүү үчүн «Жазылуу» бөлүмүн ачыңыз."),
    EventMessageTemplate("subscription.verify", "Connect to verify this location's subscription.", "Подключитесь к сети, чтобы проверить подписку этой точки.", "Осы нүктенің жазылымын тексеру үшін желіге қосылыңыз.", ky = "Бул жайдын жазылуусун текшерүү үчүн туташыңыз."),
    EventMessageTemplate("subscription.promo_invalid", "This promo code cannot be used for this location or has expired.", "Этот промокод недоступен для этой точки или срок его действия истёк.", "Бұл промокод осы нүктеге қолжетімсіз немесе мерзімі аяқталған.", ky = "Бул промокодду бул жай үчүн колдонууга болбойт же анын мөөнөтү бүткөн."),
    EventMessageTemplate("subscription.changed", "Subscription or price changed. Refresh and review the offer again.", "Подписка или цена изменились. Обновите данные и проверьте предложение ещё раз.", "Жазылым немесе баға өзгерді. Деректерді жаңартып, ұсынысты қайта тексеріңіз.", ky = "Жазылуу же баа өзгөрдү. Жаңыртып, сунушту кайра караңыз."),
    EventMessageTemplate("subscription.already_active", "This location already has active access. No additional payment was taken.", "У этой точки уже есть активный доступ. Дополнительный платёж не списан.", "Бұл нүктеге қолжетімділік қосылған. Қосымша төлем алынған жоқ.", ky = "Бул жайда активдүү мүмкүнчүлүк бар. Кошумча төлөм алынган жок."),
    EventMessageTemplate("subscription.price_unavailable", "A subscription price has not been configured for this location's region.", "Цена подписки для региона этой точки ещё не настроена.", "Осы нүктенің аймағына жазылым бағасы әлі бапталмаған.", ky = "Бул жайдын аймагы үчүн жазылуу баасы жөндөлгөн эмес."),
    EventMessageTemplate("subscription.balance", "The billing owner's available balance is insufficient, or its currency does not match this plan.", "На доступном балансе владельца недостаточно средств либо валюта баланса не совпадает с валютой тарифа.", "Иесінің қолжетімді балансында қаражат жеткіліксіз немесе баланс валютасы тариф валютасына сәйкес келмейді.", ky = "Төлөөчү ээсинин жеткиликтүү балансы жетишсиз же анын валютасы бул тарифке дал келбейт."),
    EventMessageTemplate("subscription.command_invalid", "Update the app and review the subscription offer before confirming.", "Обновите приложение и проверьте предложение подписки перед подтверждением.", "Қолданбаны жаңартып, растаудан бұрын жазылым ұсынысын тексеріңіз.", ky = "Колдонмону жаңыртып, ырастоодон мурун жазылуу сунушун караңыз."),
    EventMessageTemplate("subscription.command_conflict", "This request identifier was already used for another subscription change. Refresh before trying again.", "Идентификатор запроса уже использован для другого изменения подписки. Обновите данные перед повтором.", "Сұрау идентификаторы басқа жазылым өзгерісіне қолданылған. Қайталаудан бұрын деректерді жаңартыңыз.", ky = "Бул суроо-талап идентификатору жазылуунун башка өзгөртүүсү үчүн колдонулган. Кайра аракет кылуудан мурун жаңыртыңыз."),
    EventMessageTemplate("subscription.updated", "Subscription updated for this location.", "Подписка этой точки обновлена.", "Осы нүктенің жазылымы жаңартылды.", ky = "Бул жай үчүн жазылуу жаңыртылды."),
    EventMessageTemplate("subscription.lifetime_activated", "Lifetime access activated for this location.", "Бессрочный доступ для этой точки активирован.", "Осы нүктеге мерзімсіз қолжетімділік қосылды.", ky = "Бул жай үчүн мөөнөтсүз мүмкүнчүлүк иштетилди."),
    EventMessageTemplate("subscription.rate_limited", "Too many subscription attempts. Try again in a minute.", "Слишком много попыток. Повторите через минуту.", "Тым көп әрекет жасалды. Бір минуттан кейін қайталаңыз.", ky = "Жазылуу аракеттери өтө көп. Бир мүнөттөн кийин кайра аракет кылыңыз.")
)
