package kz.aita

internal fun visualPreferenceMessageTemplates() = listOf(
    EventMessageTemplate("support.offline.cached","Offline · saved conversations and drafts are available. Messages will refresh when the connection returns.","Не в сети · сохранённые диалоги и черновики доступны. Сообщения обновятся после подключения.","Офлайн · сақталған диалогтар мен жазбалар қолжетімді. Байланыс қалпына келгенде хабарламалар жаңартылады.", ky="Офлайн · сакталган маектер жана долбоорлор жеткиликтүү. Байланыш калыбына келгенде билдирүүлөр жаңыртылат.", tg="Офлайн · суҳбатҳо ва сиёҳнависҳои сабтшуда дастрасанд. Пас аз пайвастшавӣ паёмҳо нав мешаванд.", uz="Oflayn · saqlangan suhbatlar va qoralamalar mavjud. Aloqa tiklanganda xabarlar yangilanadi."),
    EventMessageTemplate("support.offline.empty","Offline · no conversation history has been saved here yet. You can write a draft while waiting for the connection.","Не в сети · на этом устройстве ещё нет сохранённой истории. Пока можно написать черновик.","Офлайн · бұл құрылғыда сақталған тарих әлі жоқ. Байланысты күтіп, хабарлама жаза аласыз.", ky="Офлайн · бул түзмөктө сакталган тарых азырынча жок. Байланышты күтүп долбоор жаза аласыз.", tg="Офлайн · дар ин дастгоҳ ҳоло таърих сабт нашудааст. Ҳангоми интизори пайвастшавӣ сиёҳнавис навишта метавонед.", uz="Oflayn · bu qurilmada hali tarix saqlanmagan. Aloqani kutib qoralama yozishingiz mumkin."),
    EventMessageTemplate("font.title","Text font","Шрифт текста","Мәтін қарпі", ky="Тексттин шрифти", tg="Ҳуруфи матн", uz="Matn shrifti"),
    EventMessageTemplate("font.help","Choose a font for the whole app. Your selection is saved on this device and synced with your account.","Выберите шрифт для всего приложения. Выбор сохраняется на устройстве и синхронизируется с аккаунтом.","Бүкіл қолданбаға қаріп таңдаңыз. Таңдау құрылғыда сақталып, аккаунтпен синхрондалады.", ky="Колдонмо үчүн шрифт тандаңыз. Тандоо түзмөктө сакталып, аккаунт менен шайкештешет.", tg="Барои тамоми барнома ҳуруф интихоб кунед. Интихоб дар дастгоҳ сабт ва бо ҳисоб ҳамоҳанг мешавад.", uz="Butun ilova uchun shrift tanlang. Tanlov qurilmada saqlanadi va hisob bilan sinxronlanadi."),
    EventMessageTemplate("menu.account","Your account","Ваш аккаунт","Сіздің аккаунтыңыз", ky="Сиздин аккаунт", tg="Ҳисоби шумо", uz="Hisobingiz"),
    EventMessageTemplate("menu.business","Store and trade","Магазин и торговля","Дүкен және сауда", ky="Дүкөн жана соода", tg="Мағоза ва савдо", uz="Do‘kon va savdo"),
    EventMessageTemplate("menu.work","Work","Работа","Жұмыс", ky="Жумуш", tg="Кор", uz="Ish"),
    EventMessageTemplate("menu.preferences","Preferences","Предпочтения","Баптаулар", ky="Жөндөөлөр", tg="Танзимот", uz="Sozlamalar"),
    EventMessageTemplate("menu.application","Help and application","Помощь и приложение","Көмек және қолданба", ky="Жардам жана колдонмо", tg="Кумак ва барнома", uz="Yordam va ilova"),
    EventMessageTemplate("downloads.older_empty","No previous releases for this platform yet","Предыдущих версий для этой платформы пока нет","Бұл платформа үшін алдыңғы нұсқалар әлі жоқ", ky="Бул платформа үчүн мурунку версиялар азырынча жок", tg="Барои ин платформа ҳоло версияҳои пешина нестанд", uz="Bu platforma uchun oldingi versiyalar hali yo‘q"),
)
