# Kotlin
kotlin.code.style=official
kotlin.mpp.applyDefaultHierarchyTemplate=true
kotlin.daemon.jvmargs=-Xmx3072M

# Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=false
org.gradle.caching=true

# Android
android.nonTransitiveRClass=true
android.useAndroidX=true

coroutines.version=1.10.2
ktor.version=3.3.2
serialization.version=1.7.3
