package kz.aita

fun inventoryExperienceMessage(key: String, vararg parameters: Pair<String,String>): List<LocalizedStringDataModel> {
    val words = when(key) {
        "unlimited" -> listOf("Without stock tracking", "Без учёта остатка", "Қалдық есебінсіз", "Калдык эсебисиз", "Бе ҳисоби бақия", "Qoldiq hisobisiz")
        "unlimited_help" -> listOf("Always available: sales and returns are recorded without changing stock. Transfers and write-offs require a tracked batch.", "Всегда в наличии: продажи и возвраты записываются без изменения остатка. Для перемещений и списаний нужна партия с учётом количества.", "Әрдайым бар: сату мен қайтару қалдықты өзгертпей жазылады. Тасымалдау мен есептен шығару үшін есептелетін партия керек.", "Дайыма бар: сатуу жана кайтаруу калдыкты өзгөртпөй жазылат. Которуу жана эсептен чыгаруу үчүн эсептелген партия керек.", "Ҳамеша дастрас: фурӯш ва баргардонӣ бақияро тағйир намедиҳанд. Интиқол ва аз ҳисоб баровардан партияи ҳисобшаванда мехоҳанд.", "Doim mavjud: sotuv va qaytarish qoldiqni o‘zgartirmaydi. Ko‘chirish va hisobdan chiqarish uchun hisobli partiya kerak.")
        "out_of_stock" -> listOf("Barcode {barcode}: {name} is out of stock.", "Штрихкод {barcode}: товара «{name}» нет в наличии.", "{barcode} штрихкоды: «{name}» тауар жоқ.", "{barcode} штрихкоду: «{name}» товар жок.", "Штрихкоди {barcode}: моли «{name}» мавҷуд нест.", "{barcode} shtrix-kod: «{name}» mahsulot qolmagan.")
        "weight_setup" -> listOf("Barcode {barcode}: configure {name} as a weighed item.", "Штрихкод {barcode}: настройте «{name}» как весовой товар.", "{barcode} штрихкоды: «{name}» тауарын салмақпен баптаңыз.", "{barcode} штрихкоду: «{name}» товарын таразалык кылып жөндөңүз.", "Штрихкоди {barcode}: «{name}»-ро ҳамчун моли вазнӣ танзим кунед.", "{barcode} shtrix-kod: «{name}»ni vaznli mahsulot sifatida sozlang.")
        "select_many" -> listOf("Select several", "Выбрать несколько", "Бірнешеуін таңдау", "Бир нечесин тандоо", "Интихоби чандто", "Bir nechtasini tanlash")
        "add_selected" -> listOf("Add selected", "Добавить выбранные", "Таңдалғанды қосу", "Тандалгандарды кошуу", "Иловаи интихобшуда", "Tanlanganlarni qo‘shish")
        "add_all" -> listOf("Add all parent items", "Добавить все товары родителя", "Негізгі дүкеннің барлық тауарын қосу", "Башкы дүкөндүн бардык товарын кошуу", "Иловаи ҳамаи молҳои мағозаи асосӣ", "Bosh do‘konning barcha mahsulotini qo‘shish")
        "added" -> listOf("Added", "Добавлено", "Қосылды", "Кошулду", "Илова шуд", "Qo‘shildi")
        "skipped" -> listOf("Already in this branch", "Уже есть в филиале", "Филиалда бар", "Филиалда бар", "Дар филиал ҳаст", "Filialda mavjud")
        "quick_retry" -> listOf("The item is saved. Retry to finish adding its batch and cart line.", "Товар сохранён. Повторите действие, чтобы завершить добавление партии и позиции в корзину.", "Тауар сақталды. Партия мен себетке қосуды аяқтау үшін қайталаңыз.", "Товар сакталды. Партияга жана себетке кошууну бүтүрүү үчүн кайталаңыз.", "Мол сабт шуд. Барои анҷоми иловаи партия ва сабад такрор кунед.", "Mahsulot saqlandi. Partiya va savatga qo‘shishni yakunlash uchun takrorlang.")
        "quick_quantity" -> listOf("Quantity in the Universal batch", "Количество в универсальной партии", "Әмбебап партиядағы сан", "Универсалдуу партиядагы сан", "Миқдор дар партияи универсалӣ", "Universal partiyadagi miqdor")
        "operation_quantity" -> listOf("Quantity in this transaction", "Количество в операции", "Операциядағы сан", "Операциядагы сан", "Миқдор дар амалиёт", "Amaldagi miqdor")
        "barcode_scan" -> listOf("Scan barcode", "Сканировать штрихкод", "Штрихкодты сканерлеу", "Штрихкодду сканерлөө", "Скан кардани штрихкод", "Shtrix-kodni skanerlash")
        "camera_failed" -> listOf("Could not open the camera. Check camera permission in app settings.", "Не удалось открыть камеру. Проверьте разрешение на камеру в настройках приложения.", "Камера ашылмады. Қолданба баптауларындағы рұқсатты тексеріңіз.", "Камера ачылган жок. Колдонмо жөндөөлөрүндөгү уруксатты текшериңиз.", "Камера кушода нашуд. Иҷозатро дар танзимоти барнома санҷед.", "Kamera ochilmadi. Ilova sozlamalaridagi ruxsatni tekshiring.")
        "discard_rejected" -> listOf("Discard rejected local changes", "Отменить отклонённые локальные правки", "Қабылданбаған жергілікті түзетулерді жою", "Кабыл алынбаган жергиликтүү оңдоолорду жокко чыгаруу", "Бекор кардани таҳрирҳои радшуда", "Rad etilgan mahalliy tahrirlarni bekor qilish")
        "discard_rejected_help" -> listOf("Discard this rejected edit and its dependent changes on this device? Saved server data will be loaded again.", "Отменить эту отклонённую правку и зависящие от неё локальные изменения? Данные сервера будут загружены заново.", "Осы қабылданбаған түзету мен оған тәуелді өзгерістер жойылсын ба? Сервер деректері қайта жүктеледі.", "Бул кабыл алынбаган оңдоо жана ага көз каранды өзгөрүүлөр жокко чыгарылсынбы? Сервердин маалыматы кайра жүктөлөт.", "Ин таҳрири радшуда ва тағйироти вобаста бекор шаванд? Маълумоти сервер аз нав бор мешавад.", "Ushbu rad etilgan tahrir va unga bog‘liq o‘zgarishlar bekor qilinsinmi? Server ma’lumotlari qayta yuklanadi.")
        "pending_review" -> listOf("Review saved changes", "Проверить сохранённые правки", "Сақталған өзгерістерді тексеру", "Сакталган оңдоолорду текшерүү", "Санҷиши тағйироти сабтшуда", "Saqlangan tahrirlarni tekshirish")
        else -> error("Unknown inventory message: $key")
    }
    return listOf("main" to words[0]) .plus(listOf("en","ru","kk","ky","tg","uz").zip(words)).map { (language,text) ->
        LocalizedStringDataModel(language, parameters.fold(text) { value, (name,replacement) -> value.replace("{$name}",replacement) })
    }
}
