package kz.aita

fun stockEditingMessage(key: String): List<LocalizedStringDataModel> {
    val text = when (key) {
        "item_changed" -> listOf("This item changed elsewhere. Your offline edit is kept on this device for review.", "Товар изменился после другой операции. Ваша офлайн-правка сохранена на устройстве для проверки.", "Тауар басқа жерде өзгерді. Офлайн түзету құрылғыда тексеру үшін сақталды.", "Товар башка жерде өзгөрдү. Офлайн оңдоо текшерүү үчүн түзмөктө сакталды.", "Мол дар ҷои дигар тағйир ёфт. Таҳрири офлайн барои санҷиш дар дастгоҳ нигоҳ дошта шуд.", "Mahsulot boshqa joyda o‘zgardi. Oflayn tahrir tekshirish uchun qurilmada saqlandi.")
        "batch_changed" -> listOf("This batch changed on another operation. Reopen it to use the current balance.", "Партия изменилась после другой операции. Откройте её заново, чтобы использовать актуальный остаток.", "Партия басқа операциядан кейін өзгерді. Ағымдағы қалдық үшін қайта ашыңыз.", "Партия башка операциядан кийин өзгөрдү. Учурдагы калдык үчүн кайра ачыңыз.", "Партия баъди амалиёти дигар тағйир ёфт. Барои бақияи ҷорӣ аз нав кушоед.", "Partiya boshqa amaldan keyin o‘zgardi. Joriy qoldiq uchun qayta oching.")
        "legacy_barcode" -> listOf("Older shortened barcode. Check the name and select the item manually.", "Старый сокращённый штрихкод. Проверьте название и выберите товар вручную.", "Бұрын қысқартылған штрихкод. Атауын тексеріп, тауарды қолмен таңдаңыз.", "Эски кыскартылган штрихкод. Атын текшерип, товарды кол менен тандаңыз.", "Штрихкоди кӯтоҳи кӯҳна. Номро санҷед ва молро дастӣ интихоб кунед.", "Eski qisqartirilgan shtrix-kod. Nomini tekshirib, mahsulotni qo‘lda tanlang.")
        "name" -> listOf("Enter the item name", "Введите название товара", "Тауар атауын енгізіңіз", "Товардын атын киргизиңиз", "Номи молро ворид кунед", "Mahsulot nomini kiriting")
        "barcode" -> listOf("Enter at least one barcode", "Введите хотя бы один штрихкод", "Кемінде бір штрихкод енгізіңіз", "Кеминде бир штрихкод киргизиңиз", "Ақаллан як штрихкод ворид кунед", "Kamida bitta shtrix-kod kiriting")
        "unit" -> listOf("Select a measurement unit", "Выберите единицу измерения", "Өлшем бірлігін таңдаңыз", "Өлчөө бирдигин тандаңыз", "Воҳиди ченакро интихоб кунед", "O‘lchov birligini tanlang")
        "sale_price" -> listOf("Enter a valid sale price and currency (zero is allowed)", "Укажите корректную цену продажи и валюту (можно 0)", "Сату бағасы мен валютасын енгізіңіз (0 болады)", "Сатуу баасын жана валютасын киргизиңиз (0 болот)", "Нархи фурӯш ва асъорро ворид кунед (0 мумкин)", "Sotuv narxi va valyutani kiriting (0 mumkin)")
        "supply_price" -> listOf("Enter a valid purchase price and currency (zero is allowed)", "Укажите корректную цену поставки и валюту (можно 0)", "Сатып алу бағасы мен валютасын енгізіңіз (0 болады)", "Сатып алуу баасын жана валютасын киргизиңиз (0 болот)", "Нархи харид ва асъорро ворид кунед (0 мумкин)", "Xarid narxi va valyutani kiriting (0 mumkin)")
        "wholesale" -> listOf("Check the wholesale price and minimum quantity", "Проверьте оптовую цену и минимальное количество", "Көтерме баға мен ең аз мөлшерді тексеріңіз", "Дүң бааны жана эң аз санды текшериңиз", "Нархи яклухт ва миқдори ҳадди ақалро санҷед", "Ulgurji narx va eng kam miqdorni tekshiring")
        "marketplace" -> listOf("Check the Marketplace profile fields", "Проверьте поля во вкладке «Маркетплейс»", "«Маркетплейс» қойындысындағы өрістерді тексеріңіз", "«Маркетплейс» өтмөгүндөгү талааларды текшериңиз", "Майдонҳои ҷадвали бозорро санҷед", "Market bo‘limidagi maydonlarni tekshiring")
        "duplicate" -> listOf("This barcode already belongs to another item in this store. Open that item or correct the barcode.", "Этот штрихкод уже указан у другого товара в этом магазине. Откройте тот товар или исправьте штрихкод.", "Бұл штрихкод дүкендегі басқа тауарға тиесілі. Сол тауарды ашыңыз немесе штрихкодты түзетіңіз.", "Бул штрихкод дүкөндөгү башка товарга таандык. Ал товарды ачыңыз же штрихкодду оңдоңуз.", "Ин штрихкод ба моли дигари мағоза тааллуқ дорад. Он молро кушоед ё штрихкодро ислоҳ кунед.", "Bu shtrix-kod do‘kondagi boshqa mahsulotga tegishli. O‘sha mahsulotni oching yoki kodni tuzating.")
        "saved_local" -> listOf("Saved on this device. Changes will sync when the server is available.", "Сохранено на этом устройстве. Изменения отправятся, когда сервер станет доступен.", "Осы құрылғыда сақталды. Сервер қолжетімді болғанда жіберіледі.", "Бул түзмөктө сакталды. Сервер жеткиликтүү болгондо жөнөтүлөт.", "Дар ин дастгоҳ сабт шуд. Ҳангоми дастрас шудани сервер фиристода мешавад.", "Ushbu qurilmada saqlandi. Serverga ulanish tiklanganda yuboriladi.")
        "storage" -> listOf("Could not save on this device. Keep the form open, check free storage and retry.", "Не удалось сохранить на устройстве. Не закрывайте форму, проверьте свободное место и повторите.", "Құрылғыда сақтау мүмкін болмады. Пішінді жаппай, бос орынды тексеріп қайталаңыз.", "Түзмөктө сакталган жок. Форманы жаппай, бош орунду текшерип кайталаңыз.", "Дар дастгоҳ сабт нашуд. Шаклро набандед, ҷойи холиро санҷида такрор кунед.", "Qurilmada saqlanmadi. Shaklni yopmang, bo‘sh joyni tekshirib qayta urining.")
        "retry" -> listOf("Retry", "Повторить", "Қайталау", "Кайталоо", "Такрор кардан", "Qayta urinish")
        "pending" -> listOf("Stock changes waiting to sync", "Изменения склада ожидают синхронизации", "Қойма өзгерістері синхрондауды күтуде", "Кампа өзгөрүүлөрү шайкештирүүнү күтүүдө", "Тағйироти анбор мунтазири ҳамоҳангсозӣ аст", "Ombor o‘zgarishlari sinxronlashni kutmoqda")
        "confirmation_password" -> listOf("Your current account password, not the new password", "Действующий пароль аккаунта — тот, которым вы пользуетесь сейчас, а не новый пароль", "Аккаунттың қазіргі құпиясөзі, жаңа құпиясөз емес", "Аккаунттун учурдагы сырсөзү, жаңы сырсөз эмес", "Рамзи ҷории ҳисоб, на рамзи нав", "Hisobning amaldagi paroli, yangi parol emas")
        "confirmation_help" -> listOf("Confirm with your current password and a code sent to your email or generated by your configured authenticator.", "Подтвердите действие действующим паролем и кодом из почты либо настроенного аутентификатора.", "Әрекетті қазіргі құпиясөзбен және email не бапталған аутентификатор кодымен растаңыз.", "Аракетти учурдагы сырсөз жана почтадагы же жөндөлгөн аутентификатордогу код менен ырастагыла.", "Амалро бо рамзи ҷорӣ ва коди почта ё аутентификатори танзимшуда тасдиқ кунед.", "Amalni joriy parol va email yoki sozlangan autentifikator kodi bilan tasdiqlang.")
        "authenticator_help" -> listOf("You can also use an authenticator after setting it up in Sign-in & security.", "Можно также подтверждать через аутентификатор, настроив его в разделе «Вход и безопасность».", "Аутентификаторды «Кіру және қауіпсіздік» бөлімінде баптап қолдануға болады.", "Аутентификаторду «Кирүү жана коопсуздук» бөлүмүндө жөндөп колдонсоңуз болот.", "Аутентификаторро дар бахши «Вуруд ва амният» танзим карда истифода бурдан мумкин аст.", "Autentifikatorni «Kirish va xavfsizlik» bo‘limida sozlab ishlatish mumkin.")
        "security_settings" -> listOf("Set up an authenticator", "Настроить аутентификатор", "Аутентификаторды баптау", "Аутентификаторду жөндөө", "Танзими аутентификатор", "Autentifikatorni sozlash")
        "confirmation_required" -> listOf("Enter your current password and the confirmation code", "Введите действующий пароль и код подтверждения", "Қазіргі құпиясөз бен растау кодын енгізіңіз", "Учурдагы сырсөздү жана ырастоо кодун киргизиңиз", "Рамзи ҷорӣ ва коди тасдиқро ворид кунед", "Amaldagi parol va tasdiqlash kodini kiriting")
        else -> error("Unknown stock editing message: $key")
    }
    return listOf(LocalizedStringDataModel("main", text[0])) + listOf("en", "ru", "kk", "ky", "tg", "uz").mapIndexed { i, language -> LocalizedStringDataModel(language, text[i]) }
}
