package kz.aita

internal fun AppConfiguration.pass27Text(key: String): String {
    val words = when (key) {
        "recent_searches" -> listOf("Recent searches", "Недавние запросы", "Соңғы іздеулер", "Акыркы издөөлөр", "Ҷустуҷӯҳои охирин", "Oxirgi qidiruvlar")
        "clear_recent" -> listOf("Clear history", "Очистить историю", "Тарихты тазалау", "Тарыхты тазалоо", "Тоза кардани таърих", "Tarixni tozalash")
        "print_destination" -> listOf("Printer and paper", "Принтер и бумага", "Принтер және қағаз", "Принтер жана кагаз", "Принтер ва коғаз", "Printer va qog‘oz")
        "choose_printer" -> listOf("Choose printer", "Выбрать принтер", "Принтерді таңдау", "Принтерди тандоо", "Интихоби принтер", "Printerni tanlash")
        "print_test_a4" -> listOf("Print an A4 test page", "Напечатать тестовую страницу A4", "A4 сынақ бетін басып шығару", "A4 сыноо барагын басып чыгаруу", "Чопи саҳифаи санҷишии A4", "A4 sinov sahifasini chop etish")
        "paper" -> listOf("Paper format", "Формат бумаги", "Қағаз пішімі", "Кагаз форматы", "Андозаи коғаз", "Qog‘oz formati")
        "receipt_roll" -> listOf("Receipt roll", "Чековая лента", "Чек таспасы", "Чек тасмасы", "Навори чек", "Chek lentasi")
        "browser_printer" -> listOf("The browser chooses the physical printer in its print dialog. Select the same paper size there, with scaling at 100% and headers and footers off. A website cannot read or silently reuse that printer choice.", "В браузере принтер выбирается в окне печати. Укажите там тот же формат бумаги, масштаб 100% и отключите колонтитулы. Сайт не может прочитать выбранный принтер или использовать его без диалога.", "Браузерде принтер басып шығару терезесінде таңдалады. Бірдей қағаз өлшемін, 100% масштабын орнатып, колонтитулдарды өшіріңіз. Сайт принтерді терезесіз таңдай алмайды.", "Браузерде принтер басып чыгаруу терезесинде тандалат. Кагаз өлчөмүн бирдей, масштабды 100% кылып, колонтитулдарды өчүрүңүз. Сайт принтерди диалогсуз колдоно албайт.", "Дар браузер принтерро дар равзанаи чоп интихоб кунед. Андозаи коғазро яксон, миқёсро 100% гузошта, сарлавҳаҳоро хомӯш кунед. Сайт принтерро бе равзана интихоб карда наметавонад.", "Brauzerda printer chop etish oynasida tanlanadi. Bir xil qog‘oz o‘lchami va 100% masshtabni belgilang, kolontitullarni o‘chiring. Sayt printerni oynasiz ishlata olmaydi.")
        "apply" -> listOf("Apply", "Применить", "Қолдану", "Колдонуу", "Татбиқ", "Qo‘llash")
        "discount_help" -> listOf("The discount applies to unit prices in this cart, rounded to currency precision. Promotions already included in the price are preserved.", "Скидка применяется к цене единицы товара в этой корзине с округлением до копеек. Уже действующие акции сохраняются.", "Жеңілдік осы себеттегі бірлік бағасына қолданылады және тиынға дейін дөңгелектенеді. Қолданыстағы акциялар сақталады.", "Арзандатуу себеттеги бирдик баасына колдонулуп, тыйынга тегеректелет. Учурдагы акциялар сакталат.", "Тахфиф ба нархи воҳиди мол дар сабад татбиқ шуда, то дирам яклухт мешавад. Аксияҳо нигоҳ дошта мешаванд.", "Chegirma savatdagi birlik narxiga qo‘llanib, valyuta aniqligigacha yaxlitlanadi. Mavjud aksiyalar saqlanadi.")
        "discount_error" -> listOf("Enter a percentage from 0 to 100", "Введите процент от 0 до 100", "0-ден 100-ге дейін пайыз енгізіңіз", "0дөн 100гө чейин пайыз киргизиңиз", "Фоизро аз 0 то 100 ворид кунед", "0 dan 100 gacha foiz kiriting")
        "open_store" -> listOf("Open store", "Открыть магазин", "Дүкенді ашу", "Дүкөндү ачуу", "Кушодани мағоза", "Do‘konni ochish")
        "store_pending" -> listOf("AITA is not published in this store yet. The link opens the storefront; use the file download to install AITA.", "AITA пока не опубликована в этом магазине. Ссылка открывает сам магазин; для установки AITA скачайте файл.", "AITA бұл дүкенде әлі жарияланбаған. Сілтеме дүкенді ашады; AITA орнату үшін файлды жүктеңіз.", "AITA бул дүкөндө азырынча жарыялана элек. Шилтеме дүкөндү ачат; AITA орнотуу үчүн файлды жүктөңүз.", "AITA ҳанӯз дар ин мағоза нашр нашудааст. Пайванд мағозаро мекушояд; барои насби AITA файлро боргирӣ кунед.", "AITA bu do‘konda hali nashr etilmagan. Havola do‘konni ochadi; AITA ni o‘rnatish uchun faylni yuklab oling.")
        else -> listOf(key, key, key, key, key, key)
    }
    return words[listOf("en", "ru", "kk", "ky", "tg", "uz").indexOf(stateValues.appLanguage).coerceAtLeast(0)]
}
