ALTER TABLE auth_one_time_challenges DROP CONSTRAINT auth_one_time_challenges_purpose_check;
ALTER TABLE auth_one_time_challenges ADD CONSTRAINT auth_one_time_challenges_purpose_check
CHECK (purpose IN ('PASSWORDLESS_LOGIN','PASSWORD_RECOVERY','PHONE_ALIAS','EMAIL_ALIAS',
'TOTP_RECOVERY','TOTP_RESET_NOTICE','LOGIN_EMAIL_FACTOR','SECURITY_EMAIL_PROOF',
'CONTACT_VERIFICATION','ACCOUNT_EMAIL_CHANGE_NOTICE','NEW_DEVICE_SIGN_IN_NOTICE'));
