ktor:
  deployment:
    host: "0.0.0.0"
    port: ${?AITA_PORT}
  application:
    modules:
      - kz.aita.server.ApplicationKt.module
  security:
    jwt:
      issuer: ${?AITA_JWT_ISSUER}
      audience: ${?AITA_JWT_AUDIENCE}
      realm: "AITA API"
      secret: ${?AITA_JWT_SECRET}
      accessTTL: 600000
      refreshTTL: 864000000

db:
  url: ${?AITA_DB_URL}
  user: ${?DB_USER}
  pass: ${?DB_PASS}

flyway:
  locations: "classpath:db/migration"
  baselineOnMigrate: true
  validateOnMigrate: ${?AITA_FLYWAY_VALIDATE_ON_MIGRATE}
  runOnStart: ${?AITA_FLYWAY_RUN_ON_START}
  cleanDisabled: ${?AITA_FLYWAY_CLEAN_DISABLED}

